title: Fiat 127 Campania
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg: light
    has_nav: true
    has_social: true
    profile_img: /images/127campania_sticker-803.png
    tagline: gruppo campano dei possessori di Fiat 127
    title: Fiat 127 Campania
  layout_style: overflow
  palette: orange
disableKinds:
  - RSS
